## Lendo todos os pacientes registrados nas planilhas

In [1]:
import pandas as pd
import glob
import os
from models.data_manipulator import INRDataManipulation
from sklearn.model_selection import train_test_split

In [35]:
caminho = r"G:\.shortcut-targets-by-id\1pVv4_awj3MCrGLaPaYx5OLlzmRd51R8S\GemeosDigitais_Saude\Planilhas HNE\*.xlsx" 

arquivos = glob.glob(caminho)

df_weekly_full = []
df_weekly_train = []
df_weekly_test = []

df_final_full = []
df_final_train = []
df_final_test = []

for arquivo in arquivos:
    try:        
        paciente = INRDataManipulation(path=arquivo)
        data_weekly = paciente.get_data_weekly()
        data_final = paciente.get_data_final()

        cutoff_date = data_weekly["test_date"].quantile(0.8)
        # split_index_w = int(len(data_weekly) * 0.8)
        # split_index_f = int(len(data_final) * 0.8)

        df_weekly_full.append(data_weekly.copy())
        df_weekly_train.append(data_weekly[data_weekly["test_date"] < cutoff_date])
        df_weekly_test.append(data_weekly[data_weekly["test_date"] >= cutoff_date])

        df_final_full.append(data_final.copy())
        df_final_train.append(data_final[data_final["test_date"] < cutoff_date])
        df_final_test.append(data_final[data_final["test_date"] >= cutoff_date])

    except Exception as e:
        print(f"Erro ao processar {arquivo}: {e}")

In [36]:
df_weekly_full = (
    pd.concat(df_weekly_full, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

df_weekly_train = (
    pd.concat(df_weekly_train, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

df_weekly_test = (
    pd.concat(df_weekly_test, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

df_final_full = (
    pd.concat(df_final_full, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

df_final_train = (
    pd.concat(df_final_train, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

df_final_test = (
    pd.concat(df_final_test, ignore_index=True)
      .sort_values(by=['nome_paciente', 'test_date'])
      .reset_index(drop=True)
)

In [37]:
display(df_weekly_full)
display(df_weekly_train)
display(df_weekly_test)

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real
0,ADRIANA RAMOS PESSOA,2022-10-10,0.0,1.210,0.000,2.0,3.0,0,0
1,ADRIANA RAMOS PESSOA,2022-10-17,20.0,1.430,0.220,2.0,3.0,0,0
2,ADRIANA RAMOS PESSOA,2022-10-24,22.5,1.580,0.150,2.0,3.0,0,0
3,ADRIANA RAMOS PESSOA,2022-10-31,25.0,1.500,-0.080,2.0,3.0,0,0
4,ADRIANA RAMOS PESSOA,2022-11-07,25.0,1.571,0.071,2.0,3.0,1,1
...,...,...,...,...,...,...,...,...,...
8119,ZELIA DOS SANTOS,2025-03-05,27.5,1.930,-0.040,2.5,3.5,1,1
8120,ZELIA DOS SANTOS,2025-03-12,30.0,1.900,-0.030,2.5,3.5,0,0
8121,ZELIA DOS SANTOS,2025-03-19,32.5,3.290,1.390,2.5,3.5,0,0
8122,ZELIA DOS SANTOS,2025-03-26,32.5,3.310,0.020,2.5,3.5,0,0
8123,ZELIA DOS SANTOS,2025-04-02,30.0,3.120,-0.190,2.5,3.5,0,0

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real
0,ADRIANA RAMOS PESSOA,2022-10-10,0.0,1.210,0.000,2.0,3.0,0,0
1,ADRIANA RAMOS PESSOA,2022-10-17,20.0,1.430,0.220,2.0,3.0,0,0
2,ADRIANA RAMOS PESSOA,2022-10-24,22.5,1.580,0.150,2.0,3.0,0,0
3,ADRIANA RAMOS PESSOA,2022-10-31,25.0,1.500,-0.080,2.0,3.0,0,0
4,ADRIANA RAMOS PESSOA,2022-11-07,25.0,1.571,0.071,2.0,3.0,1,1
...,...,...,...,...,...,...,...,...,...
6442,ZELIA DOS SANTOS,2024-07-10,22.5,3.910,1.290,2.5,3.5,0,0
6443,ZELIA DOS SANTOS,2024-07-17,22.5,3.086,-0.824,2.5,3.5,0,0
6444,ZELIA DOS SANTOS,2024-07-24,22.5,2.916,-0.170,2.5,3.5,1,1
6445,ZELIA DOS SANTOS,2024-07-31,22.5,2.767,-0.149,2.5,3.5,1,2
6446,ZELIA DOS SANTOS,2024-08-07,22.5,2.640,-0.127,2.5,3.5,0,0

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real
0,ADRIANA RAMOS PESSOA,2025-01-20,30.0,2.220,0.011,2.0,3.0,0,0
1,ADRIANA RAMOS PESSOA,2025-01-27,30.0,1.460,-0.760,2.0,3.0,0,0
2,ADRIANA RAMOS PESSOA,2025-02-03,30.0,1.507,0.047,2.0,3.0,1,1
3,ADRIANA RAMOS PESSOA,2025-02-10,32.5,1.600,0.093,2.0,3.0,0,0
4,ADRIANA RAMOS PESSOA,2025-02-17,35.0,1.900,0.300,2.0,3.0,0,0
...,...,...,...,...,...,...,...,...,...
1672,ZELIA DOS SANTOS,2025-03-05,27.5,1.930,-0.040,2.5,3.5,1,1
1673,ZELIA DOS SANTOS,2025-03-12,30.0,1.900,-0.030,2.5,3.5,0,0
1674,ZELIA DOS SANTOS,2025-03-19,32.5,3.290,1.390,2.5,3.5,0,0
1675,ZELIA DOS SANTOS,2025-03-26,32.5,3.310,0.020,2.5,3.5,0,0
1676,ZELIA DOS SANTOS,2025-04-02,30.0,3.120,-0.190,2.5,3.5,0,0

In [38]:
print("Tamanho df_weekly_full:", len(df_weekly_full))
print("Tamanho df_weekly_train:", len(df_weekly_train))
print("Tamanho df_weekly_test:", len(df_weekly_test), "\nValores nulos:")
print(df_weekly_full.isna().sum())

Tamanho df_weekly_full: 8124
Tamanho df_weekly_train: 6447
Tamanho df_weekly_test: 1677
Valores nulos:
nome_paciente              0
test_date                  0
dose_semanal             714
inr                        1
inr_diff                   0
low_range                  0
high_range                 0
generated                  0
weeks_since_last_real      0
dtype: int64

In [66]:
display(df_final_full)
display(df_final_train)
display(df_final_test)

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real,month,inr_lag_1,inr_lag_2,inr_lag_3,inr_lag_4,inr_roll_mean_2,inr_roll_mean_4
0,ADRIANA RAMOS PESSOA,2022-11-07,25.0,1.571,0.071,2.0,3.0,1,1,11,1.500,1.580,1.430,1.210,1.5400,1.43000
1,ADRIANA RAMOS PESSOA,2022-11-14,25.0,1.655,0.083,2.0,3.0,1,2,11,1.571,1.500,1.580,1.430,1.5355,1.52025
2,ADRIANA RAMOS PESSOA,2022-11-21,27.5,1.750,0.095,2.0,3.0,0,0,11,1.655,1.571,1.500,1.580,1.6130,1.57650
3,ADRIANA RAMOS PESSOA,2022-11-28,30.0,2.050,0.300,2.0,3.0,0,0,11,1.750,1.655,1.571,1.500,1.7025,1.61900
4,ADRIANA RAMOS PESSOA,2022-12-05,30.0,2.136,0.086,2.0,3.0,1,1,12,2.050,1.750,1.655,1.571,1.9000,1.75650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7668,ZELIA DOS SANTOS,2025-03-05,27.5,1.930,-0.040,2.5,3.5,1,1,3,1.970,2.160,2.030,2.146,2.0650,2.07650
7669,ZELIA DOS SANTOS,2025-03-12,30.0,1.900,-0.030,2.5,3.5,0,0,3,1.930,1.970,2.160,2.030,1.9500,2.02250
7670,ZELIA DOS SANTOS,2025-03-19,32.5,3.290,1.390,2.5,3.5,0,0,3,1.900,1.930,1.970,2.160,1.9150,1.99000
7671,ZELIA DOS SANTOS,2025-03-26,32.5,3.310,0.020,2.5,3.5,0,0,3,3.290,1.900,1.930,1.970,2.5950,2.27250
7672,ZELIA DOS SANTOS,2025-04-02,30.0,3.120,-0.190,2.5,3.5,0,0,4,3.310,3.290,1.900,1.930,3.3000,2.60750

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real,month,inr_lag_1,inr_lag_2,inr_lag_3,inr_lag_4,inr_roll_mean_2,inr_roll_mean_4
0,ADRIANA RAMOS PESSOA,2022-11-07,25.0,1.571,0.071,2.0,3.0,1,1,11,1.500,1.580,1.430,1.210,1.5400,1.43000
1,ADRIANA RAMOS PESSOA,2022-11-14,25.0,1.655,0.083,2.0,3.0,1,2,11,1.571,1.500,1.580,1.430,1.5355,1.52025
2,ADRIANA RAMOS PESSOA,2022-11-21,27.5,1.750,0.095,2.0,3.0,0,0,11,1.655,1.571,1.500,1.580,1.6130,1.57650
3,ADRIANA RAMOS PESSOA,2022-11-28,30.0,2.050,0.300,2.0,3.0,0,0,11,1.750,1.655,1.571,1.500,1.7025,1.61900
4,ADRIANA RAMOS PESSOA,2022-12-05,30.0,2.136,0.086,2.0,3.0,1,1,12,2.050,1.750,1.655,1.571,1.9000,1.75650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6005,ZELIA DOS SANTOS,2024-07-10,22.5,3.910,1.290,2.5,3.5,0,0,7,2.620,2.720,2.836,2.953,2.6700,2.78225
6006,ZELIA DOS SANTOS,2024-07-17,22.5,3.086,-0.824,2.5,3.5,0,0,7,3.910,2.620,2.720,2.836,3.2650,3.02150
6007,ZELIA DOS SANTOS,2024-07-24,22.5,2.916,-0.170,2.5,3.5,1,1,7,3.086,3.910,2.620,2.720,3.4980,3.08400
6008,ZELIA DOS SANTOS,2024-07-31,22.5,2.767,-0.149,2.5,3.5,1,2,7,2.916,3.086,3.910,2.620,3.0010,3.13300
6009,ZELIA DOS SANTOS,2024-08-07,22.5,2.640,-0.127,2.5,3.5,0,0,8,2.767,2.916,3.086,3.910,2.8415,3.16975

,nome_paciente,test_date,dose_semanal,inr,inr_diff,low_range,high_range,generated,weeks_since_last_real,month,inr_lag_1,inr_lag_2,inr_lag_3,inr_lag_4,inr_roll_mean_2,inr_roll_mean_4
0,ADRIANA RAMOS PESSOA,2025-01-20,30.0,2.220,0.011,2.0,3.0,0,0,1,2.209,2.200,2.340,2.266,2.2045,2.25375
1,ADRIANA RAMOS PESSOA,2025-01-27,30.0,1.460,-0.760,2.0,3.0,0,0,1,2.220,2.209,2.200,2.340,2.2145,2.24225
2,ADRIANA RAMOS PESSOA,2025-02-03,30.0,1.507,0.047,2.0,3.0,1,1,2,1.460,2.220,2.209,2.200,1.8400,2.02225
3,ADRIANA RAMOS PESSOA,2025-02-10,32.5,1.600,0.093,2.0,3.0,0,0,2,1.507,1.460,2.220,2.209,1.4835,1.84900
4,ADRIANA RAMOS PESSOA,2025-02-17,35.0,1.900,0.300,2.0,3.0,0,0,2,1.600,1.507,1.460,2.220,1.5535,1.69675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1658,ZELIA DOS SANTOS,2025-03-05,27.5,1.930,-0.040,2.5,3.5,1,1,3,1.970,2.160,2.030,2.146,2.0650,2.07650
1659,ZELIA DOS SANTOS,2025-03-12,30.0,1.900,-0.030,2.5,3.5,0,0,3,1.930,1.970,2.160,2.030,1.9500,2.02250
1660,ZELIA DOS SANTOS,2025-03-19,32.5,3.290,1.390,2.5,3.5,0,0,3,1.900,1.930,1.970,2.160,1.9150,1.99000
1661,ZELIA DOS SANTOS,2025-03-26,32.5,3.310,0.020,2.5,3.5,0,0,3,3.290,1.900,1.930,1.970,2.5950,2.27250
1662,ZELIA DOS SANTOS,2025-04-02,30.0,3.120,-0.190,2.5,3.5,0,0,4,3.310,3.290,1.900,1.930,3.3000,2.60750

In [39]:
print("Tamanho df_final_full:", len(df_final_full))
print("Tamanho df_final_train:", len(df_final_train))
print("Tamanho df_final_test:", len(df_final_test), "\nValores nulos:")
print(df_final_full.isna().sum())

Tamanho df_final_full: 7673
Tamanho df_final_train: 6010
Tamanho df_final_test: 1663
Valores nulos:
nome_paciente              0
test_date                  0
dose_semanal             539
inr                        0
inr_diff                   0
low_range                  0
high_range                 0
generated                  0
weeks_since_last_real      0
month                      0
inr_lag_1                  0
inr_lag_2                  0
inr_lag_3                  0
inr_lag_4                  0
inr_roll_mean_2            0
inr_roll_mean_4            0
dtype: int64

## Removendo valores nulos e formulando novos datasets

In [41]:
df = df_weekly_full.copy()

# Agrupamento por paciente
resumo_missing_weekly = (
    df.groupby("nome_paciente")
      .agg(
          total_registros=("dose_semanal", "size"),
          n_nan=("dose_semanal", lambda x: x.isna().sum()),
          n_validos=("dose_semanal", lambda x: x.notna().sum())
      )
)

# Calcular percentual
resumo_missing_weekly["percent_nan"] = (
    resumo_missing_weekly["n_nan"] / resumo_missing_weekly["total_registros"]
) * 100

# Ordenar do pior para o melhor
resumo_missing_weekly = resumo_missing_weekly.sort_values(
    by="percent_nan",
    ascending=False
)

display(resumo_missing_weekly.head(50))

,total_registros,n_nan,n_validos,percent_nan
nome_paciente,,,,
CARIJO CESAR FERREIRA BARACUHI,24,24,0,100.000000
GILBERTO SOARES DE PONTES,6,6,0,100.000000
HERMES TAURINO DA SILVA JUNIOR,3,3,0,100.000000
FRANCISCA LOPES DA SILVA,4,4,0,100.000000
JOSEFA ADEMILDA VALENTIM DA SILVA BATISTA,1,1,0,100.000000
NAN,11,11,0,100.000000
PAULO ROBERTO DA SILVA,19,19,0,100.000000
SAULO MORAES DE SOUZA,7,7,0,100.000000
JOANA DARC DE FRANÇA,8,7,1,87.500000
PATRICIA DA SILVA GOMES,34,29,5,85.294118
ROSIVALDO DE LIMA FERREIRA,50,40,10,80.000000
GERALDO LAURENTINO DA SILVA,85,67,18,78.823529
NORMANDO NOBERTO TARGINO,82,62,20,75.609756
MARCELO MARINHO COUTINHO,40,30,10,75.000000
IVETE DA COSTA DA SILVA MONTEIRO,93,68,25,73.118280
JOSÉ EVARISTO DA CUNHA FILHO,3,2,1,66.666667
MARGARIDA ALVES,42,24,18,57.142857
MARIA DAS NEVES,23,13,10,56.521739
IZAQUE FERREIRA DA SILVA,9,5,4,55.555556
MARIA DE FATIMA BARBOSA DA SILVA,56,30,26,53.571429
FRANKLIN COSTA DA SILVA,82,41,41,50.000000
JOSE ALIANDRO DOS SANTOS,68,32,36,47.058824
ANDREA OLIVEIRA DOS SANTOS,33,13,20,39.393939
CELIANE COSTA REIS,23,9,14,39.130435
THALITA LAYSSA GONÇALVES DE SOUZA,11,4,7,36.363636
JOSENILDA FLOR DO RÊGO,56,20,36,35.714286
DAYANNE CARLOS CORDEIRO,7,2,5,28.571429
ANTONIO DE FRANCA DA SILVA,53,15,38,28.301887
PEDRO LEITE DE SOUZA,26,7,19,26.923077
LUCIENE RAMOS DE SOUZA,27,7,20,25.925926
MARCILIO CAVALCANTE SILVA,4,1,3,25.000000
FRANCISCO DE ASSIS PEREIRA DA SILVA,61,15,46,24.590164
EMERSON SALGADO SONDAHL,21,5,16,23.809524
ROSINEIDE RENATO DA SILVA,15,3,12,20.000000
VERA LUCIA AMARO DA SILVA,50,10,40,20.000000
JOSE MARCOS BOTELHO HERMINIO,16,3,13,18.750000
JESSICA EVELYN FERREIRA DE OLIVEIRA LIMA,11,2,9,18.181818
ISABEL CRISTINA SILVA DE SOUSA,21,3,18,14.285714
GLAUCIA DIAS GOMES FERREIRA,7,1,6,14.285714
ORLANDO TAVARES,108,15,93,13.888889
MARIA DE FÁTIMA RODRIGUES AMARO,72,10,62,13.888889
IVONEIDE DE LIRA LEITE,43,5,38,11.627907
RONILDO BEZERRA DE ANDRADE,112,12,100,10.714286
EDVALDO MATIAS DE ARAUJO,72,6,66,8.333333
SEVERINO DA SILVA RAMOS,81,6,75,7.407407
VITAL JORGE DA SILVA,81,6,75,7.407407
RAMIRO ANTONIO VALENCIA,47,3,44,6.382979
ALCIDES DE CARVALHO GALVAO,20,1,19,5.000000
VENCERLAU RODRIGUES PACHECO,100,3,97,3.000000
RICARDO PONTES FIDELIS,72,1,71,1.388889

In [57]:
print("Total de pacientes registrados:", pd.unique(df_weekly_full["nome_paciente"]).shape[0])

pacientes_remover_weekly = resumo_missing_weekly[
    resumo_missing_weekly["percent_nan"] > 30
].index.tolist()

print("Pacientes a remover (weekly):", len(pacientes_remover_weekly))

df_weekly_full_filtred = df_weekly_full[~df_weekly_full["nome_paciente"].isin(pacientes_remover_weekly)]
df_weekly_train_filtred = df_weekly_train[~df_weekly_train["nome_paciente"].isin(pacientes_remover_weekly)]
df_weekly_test_filtred = df_weekly_test[~df_weekly_test["nome_paciente"].isin(pacientes_remover_weekly)]

Total de pacientes registrados: 117
Pacientes a remover (weekly): 26

In [58]:
print("Tamanho df_weekly_full_filtred:", len(df_weekly_full_filtred))
print("Tamanho df_weekly_train_filtred:", len(df_weekly_train_filtred))
print("Tamanho df_weekly_test_filtred:", len(df_weekly_test_filtred), "\nValores nulos:")
print(df_weekly_full_filtred.isna().sum())

Tamanho df_weekly_full_filtred: 7251
Tamanho df_weekly_train_filtred: 5760
Tamanho df_weekly_test_filtred: 1491
Valores nulos:
nome_paciente              0
test_date                  0
dose_semanal             143
inr                        0
inr_diff                   0
low_range                  0
high_range                 0
generated                  0
weeks_since_last_real      0
dtype: int64

In [59]:
print(df_weekly_train_filtred.isna().sum())

nome_paciente              0
test_date                  0
dose_semanal             143
inr                        0
inr_diff                   0
low_range                  0
high_range                 0
generated                  0
weeks_since_last_real      0
dtype: int64

In [60]:
print(df_weekly_test_filtred.isna().sum())

nome_paciente            0
test_date                0
dose_semanal             0
inr                      0
inr_diff                 0
low_range                0
high_range               0
generated                0
weeks_since_last_real    0
dtype: int64

In [67]:
df_weekly_full_filtred = df_weekly_full_filtred.dropna()
df_weekly_train_filtred = df_weekly_train_filtred.dropna()
df_weekly_test_filtred = df_weekly_test_filtred.dropna()

In [72]:
print("Tamanho df_weekly_full_filtred:", len(df_weekly_full_filtred))
print("Tamanho df_weekly_train_filtred:", len(df_weekly_train_filtred))
print("Tamanho df_weekly_test_filtred:", len(df_weekly_test_filtred), "\nValores nulos:")
print(df_weekly_full_filtred.isna().sum())

Tamanho df_weekly_full_filtred: 7108
Tamanho df_weekly_train_filtred: 5617
Tamanho df_weekly_test_filtred: 1491
Valores nulos:
nome_paciente            0
test_date                0
dose_semanal             0
inr                      0
inr_diff                 0
low_range                0
high_range               0
generated                0
weeks_since_last_real    0
dtype: int64

In [73]:
output_path = r"C:\Users\pedro\Desktop\GitHub\LabTEVE\datasets\weekly.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    df_weekly_train_filtred.to_excel(writer, sheet_name="train", index=False)
    df_weekly_test_filtred.to_excel(writer, sheet_name="test", index=False)
    df_weekly_full_filtred.to_excel(writer, sheet_name="full", index=False)

In [65]:
df = df_final_full.copy()

# Agrupamento por paciente
resumo_missing_final = (
    df.groupby("nome_paciente")
      .agg(
          total_registros=("dose_semanal", "size"),
          n_nan=("dose_semanal", lambda x: x.isna().sum()),
          n_validos=("dose_semanal", lambda x: x.notna().sum())
      )
)

# Calcular percentual
resumo_missing_final["percent_nan"] = (
    resumo_missing_final["n_nan"] / resumo_missing_final["total_registros"]
) * 100

# Ordenar do pior para o melhor
resumo_missing_final = resumo_missing_final.sort_values(
    by="percent_nan",
    ascending=False
)

display(resumo_missing_final.head(50))

,total_registros,n_nan,n_validos,percent_nan
nome_paciente,,,,
GILBERTO SOARES DE PONTES,2,2,0,100.000000
CARIJO CESAR FERREIRA BARACUHI,20,20,0,100.000000
SAULO MORAES DE SOUZA,3,3,0,100.000000
PAULO ROBERTO DA SILVA,15,15,0,100.000000
NAN,6,6,0,100.000000
PATRICIA DA SILVA GOMES,30,25,5,83.333333
ROSIVALDO DE LIMA FERREIRA,46,36,10,78.260870
GERALDO LAURENTINO DA SILVA,81,63,18,77.777778
JOANA DARC DE FRANÇA,4,3,1,75.000000
NORMANDO NOBERTO TARGINO,78,58,20,74.358974
MARCELO MARINHO COUTINHO,36,26,10,72.222222
IVETE DA COSTA DA SILVA MONTEIRO,89,64,25,71.910112
MARGARIDA ALVES,38,20,18,52.631579
MARIA DE FATIMA BARBOSA DA SILVA,52,26,26,50.000000
FRANKLIN COSTA DA SILVA,78,37,41,47.435897
MARIA DAS NEVES,19,9,10,47.368421
JOSE ALIANDRO DOS SANTOS,64,28,36,43.750000
ANDREA OLIVEIRA DOS SANTOS,29,9,20,31.034483
JOSENILDA FLOR DO RÊGO,52,16,36,30.769231
CELIANE COSTA REIS,19,5,14,26.315789
ANTONIO DE FRANCA DA SILVA,49,11,38,22.448980
IZAQUE FERREIRA DA SILVA,5,1,4,20.000000
FRANCISCO DE ASSIS PEREIRA DA SILVA,57,11,46,19.298246
PEDRO LEITE DE SOUZA,22,3,19,13.636364
LUCIENE RAMOS DE SOUZA,23,3,20,13.043478
VERA LUCIA AMARO DA SILVA,46,6,40,13.043478
ORLANDO TAVARES,104,11,93,10.576923
MARIA DE FÁTIMA RODRIGUES AMARO,68,6,62,8.823529
RONILDO BEZERRA DE ANDRADE,108,8,100,7.407407
EMERSON SALGADO SONDAHL,17,1,16,5.882353
EDVALDO MATIAS DE ARAUJO,68,2,66,2.941176
VITAL JORGE DA SILVA,77,2,75,2.597403
SEVERINO DA SILVA RAMOS,77,2,75,2.597403
IVONEIDE DE LIRA LEITE,39,1,38,2.564103
ANDRIELA SILVA DE BRITO,111,0,111,0.000000
ANA LUCIA TRIGUEIRO DA SILVA,53,0,53,0.000000
ALCIDES DE CARVALHO GALVAO,16,0,16,0.000000
ADRIANA RAMOS PESSOA,145,0,145,0.000000
ALEXANDRE JOSE MARTINS BORBOREMA,149,0,149,0.000000
ALINE GOMES DE FREITAS RICARDO,122,0,122,0.000000
IVANILDA DANTAS DA SILVA PEREIRA,11,0,11,0.000000
ISABEL CRISTINA SILVA DE SOUSA,17,0,17,0.000000
IRIS MARGARIDA DE ARAÚJO SILVA,39,0,39,0.000000
ILZEVAN SOARES DE OLIVEIRA,3,0,3,0.000000
HELAINE DOS SANTOS ARAUJO,144,0,144,0.000000
HELENA MARIA DO NASCIMENTO,18,0,18,0.000000
GLEICIELE FRANCISCA CANDIDO,146,0,146,0.000000
GLAUCIA PAIVA DA SILVA,112,0,112,0.000000
GILVANCI ALCANTARA FREIRE,184,0,184,0.000000
GLAUCIA DIAS GOMES FERREIRA,3,0,3,0.000000

In [61]:
print("Total de pacientes registrados:", pd.unique(df_final_full["nome_paciente"]).shape[0])

pacientes_remover_final = resumo_missing_final[
    resumo_missing_final["percent_nan"] > 30
].index.tolist()

print("Pacientes a remover (full):", len(pacientes_remover_final))

df_final_full_filtred = df_final_full[~df_final_full["nome_paciente"].isin(pacientes_remover_final)]
df_final_train_filtred = df_final_train[~df_final_train["nome_paciente"].isin(pacientes_remover_final)]
df_final_test_filtred = df_final_test[~df_final_test["nome_paciente"].isin(pacientes_remover_final)]

Total de pacientes registrados: 104
Pacientes a remover (full): 19

In [62]:
print("Tamanho df_final_full_filtred:", len(df_final_full_filtred))
print("Tamanho df_final_train_filtred:", len(df_final_train_filtred))
print("Tamanho df_final_test_filtred:", len(df_final_test_filtred), "\nValores nulos:")
print(df_final_full_filtred.isna().sum())

Tamanho df_final_full_filtred: 6931
Tamanho df_final_train_filtred: 5439
Tamanho df_final_test_filtred: 1492
Valores nulos:
nome_paciente             0
test_date                 0
dose_semanal             73
inr                       0
inr_diff                  0
low_range                 0
high_range                0
generated                 0
weeks_since_last_real     0
month                     0
inr_lag_1                 0
inr_lag_2                 0
inr_lag_3                 0
inr_lag_4                 0
inr_roll_mean_2           0
inr_roll_mean_4           0
dtype: int64

In [63]:
print(df_final_train_filtred.isna().sum())

nome_paciente             0
test_date                 0
dose_semanal             73
inr                       0
inr_diff                  0
low_range                 0
high_range                0
generated                 0
weeks_since_last_real     0
month                     0
inr_lag_1                 0
inr_lag_2                 0
inr_lag_3                 0
inr_lag_4                 0
inr_roll_mean_2           0
inr_roll_mean_4           0
dtype: int64

In [64]:
print(df_final_test_filtred.isna().sum())

nome_paciente            0
test_date                0
dose_semanal             0
inr                      0
inr_diff                 0
low_range                0
high_range               0
generated                0
weeks_since_last_real    0
month                    0
inr_lag_1                0
inr_lag_2                0
inr_lag_3                0
inr_lag_4                0
inr_roll_mean_2          0
inr_roll_mean_4          0
dtype: int64

In [74]:
df_final_full_filtred = df_final_full_filtred.dropna()
df_final_train_filtred = df_final_train_filtred.dropna()
df_final_test_filtred = df_final_test_filtred.dropna()

In [75]:
print("Tamanho df_final_full_filtred:", len(df_final_full_filtred))
print("Tamanho df_final_train_filtred:", len(df_final_train_filtred))
print("Tamanho df_final_test_filtred:", len(df_final_test_filtred), "\nValores nulos:")
print(df_final_full_filtred.isna().sum())

Tamanho df_final_full_filtred: 6858
Tamanho df_final_train_filtred: 5366
Tamanho df_final_test_filtred: 1492
Valores nulos:
nome_paciente            0
test_date                0
dose_semanal             0
inr                      0
inr_diff                 0
low_range                0
high_range               0
generated                0
weeks_since_last_real    0
month                    0
inr_lag_1                0
inr_lag_2                0
inr_lag_3                0
inr_lag_4                0
inr_roll_mean_2          0
inr_roll_mean_4          0
dtype: int64

In [76]:
output_path = r"C:\Users\pedro\Desktop\GitHub\LabTEVE\datasets\final.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    df_final_train_filtred.to_excel(writer, sheet_name="train", index=False)
    df_final_test_filtred.to_excel(writer, sheet_name="test", index=False)
    df_final_full_filtred.to_excel(writer, sheet_name="full", index=False)